---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset

  - board: nice_nano_v2
    shield: cosmos_dactyl_left
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_POINTING=y
    artifact-name: firmware-dactyl_left
  - board: nice_nano_v2
    shield: cosmos_dactyl_right
    snippet: zmk-usb-logging
    artifact-name: firmware-dactyl_right
    cmake-args: -DCONFIG_ZMK_POINTING=y

  - board: nice_nano_v2
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: firmware-sofle_left
  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: firmware-sofl_right
