---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset

  - board: nice_nano_v2
    shield: cosmos_dactyl_left nice_oled
    cmake-args: -DCONFIG_ZMK_POINTING=y
    artifact-name: firmware-dactyl_left
  - board: nice_nano_v2
    shield: cosmos_dactyl_right nice_oled
    cmake-args: -DCONFIG_ZMK_POINTING=y
    artifact-name: firmware-dactyl_right

  - board: nice_nano_v2
    shield: sofle_left nice_oled
    artifact-name: firmware-sofle_left
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    artifact-name: firmware-sofl_right
