---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice-nano_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao-ble_reset 

  - board: seeeduino_xiao_ble
    shield: cosmos_dactyl_dongle 
    artifact-name: firmware-dactyl_dongle
  - board: nice_nano_v2
    shield: cosmos_dactyl_left nice_oled
    cmake-args: -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: firmware-dactyl_left
  - board: nice_nano_v2
    shield: cosmos_dactyl_right nice_oled
    cmake-args: -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: firmware-dactyl_right

  - board: seeeduino_xiao_ble
    shield: sofle_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: firmware-sofle_dongle
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    artifact-name: firmware-sofle_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: firmware-sofl_right
    snippet: zmk-usb-logging
