---
include:
  - board: nice_nano
    shield: settings_reset
    artifact-name: nice-nano_reset
  - board: xiao_ble
    shield: settings_reset
    artifact-name: xiao-ble_reset

  - board: nice_nano
    shield: cosmos_dactyl_left nice_oled
    cmake-args: -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_SPLIT=y
    artifact-name: firmware-dactyl_left
  - board: nice_nano
    shield: cosmos_dactyl_right nice_oled
    cmake-args: -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: firmware-dactyl_right

  - board: nice_nano
    shield: sofle_left nice_oled
    artifact-name: firmware-sofle_left
  - board: nice_nano
    shield: sofle_right nice_oled
    artifact-name: firmware-sofle_right

  - board: nice_nano
    shield: corne_left nice_oled
    artifact-name: firmware-corne_left
  - board: nice_nano
    shield: corne_right nice_oled
    artifact-name: firmware-corne_right
